version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_ROOT_PASSWORD
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
    ports:
      - "8087:80"
    depends_on:
      - mysql
    container_name: phpmyadmin
  
# login ssh to container mysql
# mysql -u root -p
# GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
